apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: week7
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # nếu muốn web pod kết nối trực tiếp (stateful)
