apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: week7-cicd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danqNg0911/week7_ci-cd_with_week1_web.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
